FROM ros:jazzy
ARG USERNAME=USERNAME
ARG USER_UID=1001
ARG USER_GID=$USER_UID

# Delete user if it exists in container (e.g Ubuntu Noble: ubuntu)
RUN if id -u $USER_UID ; then userdel `id -un $USER_UID` ; fi

# Create the user
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    #
    # [Optional] Add sudo support. Omit if you don't need to install software after connecting.
    && apt-get update \
    && apt-get install -y sudo \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME

RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y python3-pip
ENV SHELL /bin/bash

USER $USERNAME
RUN sudo apt-get update && sudo apt-get install -y curl lsb-release gnupg

RUN sudo apt install -y ros-jazzy-rmw-cyclonedds-cpp

RUN mkdir -p ~/ros2_ws/src

RUN echo "source /opt/ros/jazzy/local_setup.bash" >> ~/.bashrc
RUN echo "source /home/${USERNAME}/ros2_ws/install/local_setup.bash" >> ~/.bashrc
RUN echo "export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp" >> ~/.bashrc

CMD ["/bin/bash"]