/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_FLOATARRAY_PB_H_INCLUDED
#define PB_FLOATARRAY_PB_H_INCLUDED
#include "pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _FloatArray {
    pb_callback_t data;
} FloatArray;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define FloatArray_init_default                  {{{NULL}, NULL}}
#define FloatArray_init_zero                     {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define FloatArray_data_tag                      1

/* Struct field encoding specification for nanopb */
#define FloatArray_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, FLOAT,    data,              1)
#define FloatArray_CALLBACK pb_default_field_callback
#define FloatArray_DEFAULT NULL

extern const pb_msgdesc_t FloatArray_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define FloatArray_fields &FloatArray_msg

/* Maximum encoded size of messages (where known) */
/* FloatArray_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
